-- Supabase setup for TBCheck AI
-- Run this in the Supabase SQL editor.

create extension if not exists "pgcrypto";

grant usage on schema public to anon, authenticated;

create table if not exists public.screening_histories (
  id bigint generated by default as identity primary key,
  user_id text not null,
  selected_symptoms jsonb not null default '[]'::jsonb,
  cf_score_raw double precision not null default 0,
  cf_score_percentage double precision not null default 0,
  risk_level varchar(20) not null default 'Rendah',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop policy if exists "Users can read own history" on public.screening_histories;
drop policy if exists "Users can insert own history" on public.screening_histories;
drop policy if exists "Users can update own history" on public.screening_histories;

alter table if exists public.screening_histories
  alter column user_id type text using user_id::text;

alter table if exists public.screening_histories
  alter column selected_symptoms type jsonb using selected_symptoms::jsonb;

alter table if exists public.screening_histories
  alter column cf_score_raw type double precision using cf_score_raw::double precision;

alter table if exists public.screening_histories
  alter column cf_score_percentage type double precision using cf_score_percentage::double precision;

alter table if exists public.screening_histories
  alter column risk_level type varchar(20) using risk_level::varchar(20);

create index if not exists screening_histories_user_id_idx
  on public.screening_histories (user_id);

create index if not exists screening_histories_created_at_idx
  on public.screening_histories (created_at desc);

alter table public.screening_histories enable row level security;

grant select, insert, update, delete on table public.screening_histories to authenticated;
grant usage, select on sequence public.screening_histories_id_seq to authenticated;
create policy "Users can read own history"
on public.screening_histories
for select
using (user_id = auth.uid()::text);

create policy "Users can insert own history"
on public.screening_histories
for insert
with check (user_id = auth.uid()::text);

create policy "Users can update own history"
on public.screening_histories
for update
using (user_id = auth.uid()::text)
with check (user_id = auth.uid()::text);

create or replace function public.calculate_screening(selected_symptoms text[])
returns table (
  cf_score_raw double precision,
  cf_score_percentage double precision,
  risk_level text,
  ai_advice text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cf_raw double precision := 0;
  v_cf_percentage double precision := 0;
  v_risk_level text := 'Rendah';
  v_ai_advice text := '';
  symptom_code text;
begin
  if selected_symptoms is null then
    selected_symptoms := array[]::text[];
  end if;

  foreach symptom_code in array selected_symptoms loop
    case symptom_code
      when 'G01' then v_cf_raw := v_cf_raw + 0.18;
      when 'G02' then v_cf_raw := v_cf_raw + 0.20;
      when 'G03' then v_cf_raw := v_cf_raw + 0.10;
      when 'G04' then v_cf_raw := v_cf_raw + 0.14;
      when 'G05' then v_cf_raw := v_cf_raw + 0.10;
      when 'G06' then v_cf_raw := v_cf_raw + 0.08;
      when 'G07' then v_cf_raw := v_cf_raw + 0.12;
      when 'G08' then v_cf_raw := v_cf_raw + 0.10;
      when 'R01' then v_cf_raw := v_cf_raw + 0.08;
      when 'R02' then v_cf_raw := v_cf_raw + 0.06;
      when 'R03' then v_cf_raw := v_cf_raw + 0.07;
      when 'R04' then v_cf_raw := v_cf_raw + 0.05;
      when 'R05' then v_cf_raw := v_cf_raw + 0.05;
      when 'K01' then v_cf_raw := v_cf_raw + 0.06;
      when 'K02' then v_cf_raw := v_cf_raw + 0.05;
      when 'K03' then v_cf_raw := v_cf_raw + 0.10;
      when 'K04' then v_cf_raw := v_cf_raw + 0.10;
      else v_cf_raw := v_cf_raw + 0;
    end case;
  end loop;

  if v_cf_raw > 1 then
    v_cf_raw := 1;
  end if;

  v_cf_percentage := round((v_cf_raw * 100)::numeric, 1)::double precision;

  if v_cf_percentage >= 60 then
    v_risk_level := 'Tinggi';
    v_ai_advice := 'Risiko TBC tinggi. Segera periksa ke fasilitas kesehatan untuk evaluasi lanjutan.';
  elsif v_cf_percentage >= 30 then
    v_risk_level := 'Sedang';
    v_ai_advice := 'Ada sejumlah faktor yang perlu diwaspadai. Pantau gejala dan konsultasikan ke tenaga kesehatan.';
  else
    v_risk_level := 'Rendah';
    v_ai_advice := 'Risiko terdeteksi rendah, tetapi tetap jaga kesehatan dan lakukan skrining ulang bila gejala muncul.';
  end if;

  return query
  select v_cf_raw, v_cf_percentage, v_risk_level, v_ai_advice;
end;
$$;

grant execute on function public.calculate_screening(text[]) to authenticated;
